services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - loan-net

  fundo.applications.webapi:
    build:
      context: .
      dockerfile: Fundo.Applications.WebApi/Dockerfile
    ports:
      - "5000:80"
    networks:
      - loan-net

networks:
  loan-net:
    driver: bridge
